#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidChips.TestApp.Resource", IsApplication=true)]

namespace AndroidChips.TestApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int avatarPosition = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int chipBackground = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int chipBackgroundPressed = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int chipDelete = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int chipEntryErrorHint = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int chipFontSize = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int chipHeight = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int chipOverLimitErrorHint = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int chipPadding = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int disableDelete = 2130771977;
			
			// aapt resource value: 0x7f01000b
			public const int imageSpanAlignment = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int invalidChipBackground = 2130771978;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int chip_height = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int chip_icon_margin_start = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int chip_padding = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int chip_subtitle_padding_start = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int chip_text_size = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int chip_title_padding_start = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int extra_chip_height = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int line_spacing_extra = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int padding_no_picture = 2131034120;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int chip_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int chip_background_invalid = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int chip_background_selected = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int chip_delete = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_contact_picture = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int list_item_font_primary = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int list_item_font_secondary = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int no_avatar_picture = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int baseline = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int bottom = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int end = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int phone_retv = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int show_all = 2131230725;
			
			// aapt resource value: 0x7f080001
			public const int start = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int text1 = 2131230726;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int chips_max_lines = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int chips_alternate_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int chips_recipient_dropdown_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int copy_chip_dialog_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int more_item = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int copy_email = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int copy_number = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int done = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int email_addresses = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int error_invalid_chips = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int error_over_chips_limit = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int more_string = 2130968586;
			
			// aapt resource value: 0x7f040004
			public const int phone_numbers = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int ChipIconStyle = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int ChipSubtitleStyle = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int ChipTitleStyle = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int RecipientEditTextView = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecipientEditTextView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int RecipientEditTextView_avatarPosition = 0;
			
			// aapt resource value: 1
			public const int RecipientEditTextView_chipBackground = 1;
			
			// aapt resource value: 2
			public const int RecipientEditTextView_chipBackgroundPressed = 2;
			
			// aapt resource value: 3
			public const int RecipientEditTextView_chipDelete = 3;
			
			// aapt resource value: 5
			public const int RecipientEditTextView_chipEntryErrorHint = 5;
			
			// aapt resource value: 4
			public const int RecipientEditTextView_chipFontSize = 4;
			
			// aapt resource value: 7
			public const int RecipientEditTextView_chipHeight = 7;
			
			// aapt resource value: 6
			public const int RecipientEditTextView_chipOverLimitErrorHint = 6;
			
			// aapt resource value: 8
			public const int RecipientEditTextView_chipPadding = 8;
			
			// aapt resource value: 9
			public const int RecipientEditTextView_disableDelete = 9;
			
			// aapt resource value: 11
			public const int RecipientEditTextView_imageSpanAlignment = 11;
			
			// aapt resource value: 10
			public const int RecipientEditTextView_invalidChipBackground = 10;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
